### ISSUE TITLE
默认的guard name 无法读取

### ISSUE THREAD

**Issue by ruoge3s** [donjan-deng/hyperf-permission#1]
https://github.com/donjan-deng/hyperf-permission/blob/master/src/Guard.php#L47

```
    public static function getDefaultName($class): string
    {
        $default = 'web'; // 这个地方没有读取配置啊

        return static::getNames($class)->first() ?: $default;
    }
```

https://github.com/spatie/laravel-permission/blob/master/src/Guard.php#L47

**Comment by donjan-deng** [comment]
Hyperf是没有Auth组件实现认证的，没有看守器，只是保留了此功能，以便以后结合使用。就算读取配置也是一个固定值，没有任何作用。
