### ISSUE TITLE
2.0版本给用户赋角色报错

### ISSUE THREAD

**Issue by lxyzsl** [donjan-deng/hyperf-permission#11]
![image](https://user-images.githubusercontent.com/17881085/96248120-a972e380-0fdd-11eb-9b11-6c1a0370a4e4.png)
![image](https://user-images.githubusercontent.com/17881085/96248142-b0015b00-0fdd-11eb-99d2-8046dc283085.png)
是不是哪里使用错了

**Comment by lxyzsl** [comment]
model_id,model_type又是什么

**Comment by donjan-deng** [comment]
贴出创建Role的代码，使用Role的create方法创建角色
