### ISSUE TITLE
多进程的时候，权限缓存有BUG

### ISSUE THREAD

**Issue by zhenhua2340** [donjan-deng/hyperf-permission#13]
文件 `/src/PermissionRegistrar.php` 里面的这个方法

```
    public function getPermissions(array $params = []): Collection {
        if ($this->permissions === null) {
            if ($this->cache->has(self::$cacheKey)) {
                $this->permissions = $this->cache->get(self::$cacheKey);
            } else {
                $this->permissions = $this->getPermissionClass()
                        ->with('roles')
                        ->get();
                $this->cache->set(self::$cacheKey, $this->permissions, self::$cacheExpirationTime);
            }
        }

        $permissions = clone $this->permissions;

        foreach ($params as $attr => $value) {
            $permissions = $permissions->where($attr, $value);
        }

        return $permissions;
    }
```

 ` if ($this->permissions === null) {`  这个只会判断 当前进程里对象的属性

`forgetCachedPermissions` 方法删除也是当前进程里面 对象的 `permissions ` 属性，

当多进程的时候，修改权限后，调用``forgetCachedPermissions` `删除，
再用`getPermissions`这个方法，获取的缓存数据就会有问题，只有访问当前处理进程的时候，数据才是最新
而其它进程里的数据还是老数据

**Comment by eric-strive** [comment]
请问这个解决了吗，我这边也发现这个问题了，只有重启才行，这个有好的决绝办法吗；

**Comment by donjan-deng** [comment]
@eric-strive 详细说下实现这个bug的步聚

**Comment by eric-strive** [comment]
下面是一段角色分配菜单的代码

public function assigningMenu()
    {
        return $this->apiResponse(function () {
            $id      = (int)$this->request->input('id');
            $menuIds = $this->request->input('m_ids');
            $mids    = array_filter($menuIds, function ($value) {
                return is_int($value);
            });
            Role::find($id)->permissions()->sync($mids);
            ApplicationContext::getContainer()->get(PermissionRegistrar::class)->forgetCachedPermissions();
            return '分配成功';
        });
    }

为了每次分配菜单后实时生效；需要分配后清除权限缓存
ApplicationContext::getContainer()->get(PermissionRegistrar::class)->forgetCachedPermissions();
分配后有时候生效时不生效，感觉应该是不同进程引起的

**Comment by eric-strive** [comment]
worker_num设置为1时就不会有这种问题

**Comment by donjan-deng** [comment]
使用组件的syncPermissions方法，不要用Eloquent ORM的方法去直接操作数据库

**Comment by eric-strive** [comment]
嗯，我直接没用这个缓存，每次权限都是重新实例化权限对象，就不会有这种问题了。
