### ISSUE TITLE
2.0版本获取用户所对应的角色无效

### ISSUE THREAD

**Issue by qinjintian** [donjan-deng/hyperf-permission#14]
使用这个方法时$user->roles()->get();打印出来的SQL是这样的

> `select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id`, `model_has_roles`.`model_type` as `pivot_model_type` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` = '1' and `model_has_roles`.`model_type` = 'App\Model\User'`

，而laravel同样的方法打印出来是这样的

> select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id`, `model_has_roles`.`model_type` as `pivot_model_type` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` = '1' and `model_has_roles`.`model_type` = 'App\\Model\\User'

问题在于` 'App\Model\User'`没有转义，应该这样才对 `'App\\Model\\User'`

**Comment by donjan-deng** [comment]
```
$user->roles;
$user->getRoleNames();
$user->roles()->get();
```
均可获取角色列表，未出错

**Comment by qinjintian** [comment]
> $user->roles;
> $user->getRoleNames();
> $user->roles()->get();

我用了你以上的示例均为能正常获取都数据，实际上数据库是有数据的，愿意是 `model_has_roles.model_type = 'App\Model\User'` 是错的，需要改为` model_has_roles.model_type = 'App\\Model\\User'` 才能查询出数据，你可以把SQL复制到MySQL客户端执行看看是否能查询得出？@donjan-deng

**Comment by donjan-deng** [comment]
此问题已与本项目无关，建议学习Eloquent ORM是如何执行SQL的
