### ISSUE TITLE
权限也可能是按钮

### ISSUE THREAD

**Issue by ijackwu** [donjan-deng/hyperf-permission#2]
菜单和权限分离或许会更好

如题，菜单也可能是按钮，这个时候不一定要展示到菜单

或者添加标识，区分菜单或者按钮

**Comment by donjan-deng** [comment]
不是必填，不填就不会出现

**Comment by qinjintian** [comment]
加一个type字段，0 => 折叠菜单（点击会展开子集菜单，点击只会展开和收缩，不带链接）， 1 => 菜单 (带URL)，2 => 页面按钮，这样就可以解决了
