### ISSUE TITLE
角色绑定权限

### ISSUE THREAD

**Issue by wuqinqiang** [donjan-deng/hyperf-permission#3]
有点疑惑 这里如果传入的数组是权限的主键id它是咋么找到对应权限的
![屏幕快照 2020-01-08 上午11 09 38](https://user-images.githubusercontent.com/36129334/71947328-840fa880-3207-11ea-917b-939a5d23c000.png)
<img width="711" alt="屏幕快照 2020-01-08 上午11 09 16" src="https://user-images.githubusercontent.com/36129334/71947336-896cf300-3207-11ea-9613-1333b5cad003.png">

这里那里有按照id查

<img width="834" alt="屏幕快照 2020-01-08 上午11 11 03" src="https://user-images.githubusercontent.com/36129334/71947365-95f14b80-3207-11ea-8e69-fc4aaaba5b4f.png">

**Comment by donjan-deng** [comment]
如果是传的id数组，map方法传入getStoredPermission的参数是单个id，而非数据，你应该看
```php
        if (is_numeric($permissions)) {
            return $permissionClass->findById($permissions, $this->getDefaultGuardName());
        }
```
