### ISSUE TITLE
user->getMenu()有个bug，当设置url为null时，获取的数据有问题

### ISSUE THREAD

**Issue by qq781548819** [donjan-deng/hyperf-permission#6]
全部都为菜单时：

`{
    "code": 0,
    "msg": "success",
    "data": [
        {
            "id": 2,
            "parent_id": 0,
            "name": "user:list",
            "display_name": "用户管理",
            "url": "system/user",
            "guard_name": "web",
            "sort": 99,
            "created_at": "2020-02-21 15:26:22",
            "updated_at": "2020-02-21 15:26:22",
            "child": [
                {
                    "id": 3,
                    "parent_id": 2,
                    "name": "user:add",
                    "display_name": "创建用户",
                    "url": "system/user/add",
                    "guard_name": "web",
                    "sort": 98,
                    "created_at": "2020-02-21 15:26:23",
                    "updated_at": "2020-02-21 15:26:23",
                    "child": [],
                    "pivot": {
                        "role_id": 4,
                        "permission_id": 3
                    }
                },
                {
                    "id": 4,
                    "parent_id": 2,
                    "name": "user:edit",
                    "display_name": "编辑用户",
                    "url": "system/user/edit",
                    "guard_name": "web",
                    "sort": 97,
                    "created_at": "2020-02-21 15:26:23",
                    "updated_at": "2020-02-21 15:26:23",
                    "child": [],
                    "pivot": {
                        "role_id": 4,
                        "permission_id": 4
                    }
                },
                {
                    "id": 5,
                    "parent_id": 2,
                    "name": "user:del",
                    "display_name": "删除用户",
                    "url": "system/user/del",
                    "guard_name": "web",
                    "sort": 96,
                    "created_at": "2020-02-21 15:26:23",
                    "updated_at": "2020-02-21 15:26:23",
                    "child": [],
                    "pivot": {
                        "role_id": 4,
                        "permission_id": 5
                    }
                }
            ],
            "pivot": {
                "role_id": 4,
                "permission_id": 2
            }
        }
    ]
}`

当设置url为null时
`{
    "code": 0,
    "msg": "success",
    "data": [
        {
            "id": 2,
            "parent_id": 0,
            "name": "user:list",
            "display_name": "用户管理",
            "url": "system/user",
            "guard_name": "web",
            "sort": 99,
            "created_at": "2020-02-21 15:26:22",
            "updated_at": "2020-02-21 15:26:22",
            "child": {
                "1": {
                    "id": 4,
                    "parent_id": 2,
                    "name": "user:edit",
                    "display_name": "编辑用户",
                    "url": "system/user/edit",
                    "guard_name": "web",
                    "sort": 97,
                    "created_at": "2020-02-21 15:26:23",
                    "updated_at": "2020-02-21 15:26:23",
                    "child": [],
                    "pivot": {
                        "role_id": 4,
                        "permission_id": 4
                    }
                },
                "2": {
                    "id": 5,
                    "parent_id": 2,
                    "name": "user:del",
                    "display_name": "删除用户",
                    "url": "system/user/del",
                    "guard_name": "web",
                    "sort": 96,
                    "created_at": "2020-02-21 15:26:23",
                    "updated_at": "2020-02-21 15:26:23",
                    "child": [],
                    "pivot": {
                        "role_id": 4,
                        "permission_id": 5
                    }
                }
            },
            "pivot": {
                "role_id": 4,
                "permission_id": 2
            }
        }
    ]
}`

**Comment by qq781548819** [comment]
数据处理转换数组类型不对，索引数组跟关联数组都有出现

**Comment by donjan-deng** [comment]
该方法没有参数
