### ISSUE TITLE
composer安装报错

### ISSUE THREAD

**Issue by 869413421** [donjan-deng/hyperf-permission#7]
Problem 1
    - Installation request for donjan-deng/hyperf-permission ^1.1 -> satisfiable by donjan-deng/hyperf-permission[1.1.0].
    - Conclusion: remove hyperf/utils v1.1.18
    - Conclusion: don't install hyperf/utils v1.1.18
    - donjan-deng/hyperf-permission 1.1.0 requires hyperf/utils ~1.1.22 -> satisfiable by hyperf/utils[1.1.x-dev, v1.1.22, v1.1.24].
    - Can only install one of: hyperf/utils[1.1.x-dev, v1.1.18].
    - Can only install one of: hyperf/utils[v1.1.22, v1.1.18].
    - Can only install one of: hyperf/utils[v1.1.24, v1.1.18].
    - Installation request for hyperf/utils (locked at v1.1.18) -> satisfiable by hyperf/utils[v1.1.18].

**Comment by donjan-deng** [comment]
1.1.22以前的hyperf使用旧版本，`composer require donjan-deng/hyperf-permission ~1.0`

**Comment by donjan-deng** [comment]
1.1.22以前的hyperf使用旧版本，`composer require donjan-deng/hyperf-permission ~1.0`

**Comment by 869413421** [comment]
> 1.1.22以前的hyperf使用旧版本，`composer require donjan-deng/hyperf-permission ~1.0`

用了一下，感觉迁移文件可以考虑增加一些默认值和索引。
